// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rprbwlywuzcksapgyayl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcmJ3bHl3dXpja3NhcGd5YXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODU1ODAsImV4cCI6MjA3Mjc2MTU4MH0.0Hz_cmWgEXMRqaV9VtNXH3CGQH3X3Ctk-LLEWY937OI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});